application: vvs-chat-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.app

- url: /_ah/mail/.+
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: latest

inbound_services:
- mail